include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_const_constructors
    - prefer_final_fields
    - use_super_parameters
    - sort_pub_dependencies
    - cancel_subscriptions
    - close_sinks
