targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          include_if_null: false
          checked: false
          field_rename: none
          create_to_json: true
          create_factory: true
